'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { acceptEula } from '@/app/actions/tasks'
import Link from 'next/link'

export default function EULA() {
  const [accepting, setAccepting] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const router = useRouter()

  const handleScroll = (e) => {
    const el = e.target
    const isBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 40
    if (isBottom) setScrolled(true)
  }

  const handleAccept = async () => {
    setAccepting(true)
    const { data: { session } } = await supabase.auth.getSession()
    if (!session) { router.push('/login'); return }
    await acceptEula(session.user.id)
    router.push('/')
  }

  const handleDecline = async () => {
    await supabase.auth.signOut()
    router.push('/login')
  }

  const sections = [
    {
      title: '1. Beta Testing Agreement',
      content: 'Study with Aguila is currently in closed beta testing. By accessing this application, you acknowledge that you are an authorized beta tester. You agree not to share your login credentials or grant access to unauthorized individuals. This beta version may contain bugs, incomplete features, or unexpected behavior.'
    },
    {
      title: '2. Data Collection and Privacy',
      content: 'We collect and store your email address, uploaded PDF documents, chat messages, quiz results, and study session data. This data is used solely to provide and improve the Study with Aguila service. Your PDF content is processed by AI systems (Google Gemini for embeddings, OpenRouter-hosted models for responses). We do not sell your data to third parties. You may request deletion of your account and associated data at any time by contacting the administrator.'
    },
    {
      title: '3. Acceptable Use',
      content: 'You agree to use Study with Aguila only for lawful educational purposes. You must not upload content that is illegal, offensive, violates copyright, or contains malware. You must not attempt to reverse-engineer, scrape, or abuse the platform. Academic dishonesty — such as submitting AI-generated work as entirely your own without disclosure — remains your sole ethical responsibility.'
    },
    {
      title: '4. AI-Generated Content Disclaimer',
      content: 'Responses generated by Aguila are produced by large language models and may contain errors, inaccuracies, or outdated information. AI-generated content should be used as a study aid and verified against authoritative academic sources. The application administrators are not responsible for decisions made based on AI output. Always verify critical information independently.'
    },
    {
      title: '5. Intellectual Property',
      content: 'You retain full ownership of any PDF documents and notes you upload. By uploading content, you grant Study with Aguila a limited, non-exclusive license to process that content for the purpose of providing the service. The Study with Aguila interface, mascot character (Agui), and underlying platform remain the intellectual property of the application developer.'
    },
    {
      title: '6. Limitation of Liability',
      content: 'Study with Aguila is provided on an "as-is" basis during the beta period. The developer makes no warranties regarding uptime, data persistence, or accuracy. The developer shall not be liable for any loss of data, study time, or academic outcomes resulting from use or unavailability of this service. Use this application as a supplementary study tool, not as your sole source of academic preparation.'
    },
    {
      title: '7. Changes to These Terms',
      content: 'These terms may be updated as the application evolves. You will be notified of significant changes and may be asked to re-accept. Continued use of the application after notification constitutes acceptance of the updated terms.'
    },
    {
      title: '8. Contact',
      content: 'For questions, data deletion requests, or to report issues, contact the application administrator directly. As this is a closed beta, support is provided on a best-effort basis.'
    },
  ]

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 flex flex-col">
      <header className="flex-shrink-0 border-b border-neutral-800 px-6 py-4 flex items-center gap-4">
        <div className="flex items-center gap-3">
          <svg viewBox="0 0 48 52" xmlns="http://www.w3.org/2000/svg" className="w-6 h-6">
            <polygon points="18,12 21,4 24,11" fill="#5C3D11"/>
            <ellipse cx="24" cy="23" rx="13" ry="12" fill="#8B5E2A"/>
            <ellipse cx="25" cy="25" rx="8.5" ry="7.5" fill="#F2DEB0"/>
            <polygon points="33,22 42,25 33,28" fill="#F5C218"/>
          </svg>
          <span className="font-bold text-white text-sm">Study with Aguila</span>
        </div>
        <span className="text-neutral-700 text-xs">|</span>
        <span className="text-neutral-400 text-sm">End User License Agreement</span>
      </header>

      <div className="flex-1 flex flex-col max-w-2xl mx-auto w-full px-6 py-8 gap-6">
        <div>
          <h1 className="text-2xl font-bold text-white">Terms of Use</h1>
          <p className="text-neutral-500 text-sm mt-1.5">Version 1.0 — Beta</p>
          <p className="text-neutral-400 text-sm mt-3 leading-relaxed">
            Please read these terms carefully before using Study with Aguila.
            Scroll to the bottom to accept.
          </p>
        </div>

        <div
          onScroll={handleScroll}
          className="flex-1 overflow-y-auto max-h-[50vh] bg-neutral-900 border border-neutral-800 rounded-2xl p-5 space-y-6">
          {sections.map((section, i) => (
            <div key={i}>
              <h3 className="text-sm font-semibold text-white mb-2">{section.title}</h3>
              <p className="text-sm text-neutral-400 leading-relaxed">{section.content}</p>
            </div>
          ))}
          <div className="pt-4 border-t border-neutral-800">
            <p className="text-xs text-neutral-600 text-center">End of Terms — Version 1.0</p>
          </div>
        </div>

        {!scrolled && (
          <p className="text-xs text-neutral-600 text-center">Scroll to the bottom of the terms to accept.</p>
        )}

        <div className="flex gap-3">
          <button onClick={handleDecline}
            className="flex-1 py-3 rounded-xl border border-neutral-700 text-neutral-400 hover:text-white hover:border-neutral-600 text-sm font-medium transition-all">
            Decline and sign out
          </button>
          <button onClick={handleAccept} disabled={!scrolled || accepting}
            className="flex-1 py-3 rounded-xl bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-700 disabled:opacity-40 transition-all">
            {accepting ? 'Saving...' : 'I accept these terms'}
          </button>
        </div>
      </div>
    </main>
  )
}